image: docker:latest

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/silver_lily/voluptas .
    - docker push registry.gitlab.com/silver_lily/voluptas
